#pragma once 

#define VEKTOR_MOUSE_BUTTON_1         0
#define VEKTOR_MOUSE_BUTTON_2         1
#define VEKTOR_MOUSE_BUTTON_3         2
#define VEKTOR_MOUSE_BUTTON_4         3
#define VEKTOR_MOUSE_BUTTON_5         4
#define VEKTOR_MOUSE_BUTTON_6         5 
#define VEKTOR_MOUSE_BUTTON_7         6
#define VEKTOR_MOUSE_BUTTON_8         7

#define VEKTOR_MOUSE_BUTTON_LEFT      VEKTOR_MOUSE_BUTTON_1
#define VEKTOR_MOUSE_BUTTON_RIGHT     VEKTOR_MOUSE_BUTTON_2
#define VEKTOR_MOUSE_BUTTON_MIDDLE    VEKTOR_MOUSE_BUTTON_3

#define VEKTOR_MOUSE_BUTTON_LAST      VEKTOR_MOUSE_BUTTON_8