#pragma once

#if !defined(IMGUI_IMPL_OPENGL_LOADER_GLAD) && !defined(IMGUI_IMPL_OPENGL_LOADER_GLEW) && !defined(IMGUI_IMPL_OPENGL_LOADER_GL3W) && !defined(IMGUI_IMPL_OPENGL_LOADER_CUSTOM)
#define IMGUI_IMPL_OPENGL_LOADER_GL3W
#endif

